// Alle inhoud overgenomen uit 4-weken_cyclusmenu.pdf.
//
// Elk ingredient heeft een `display`-tekst (exact zoals in de PDF, voor op de
// receptpagina) en, waar zinvol, een `key` + `qty` + `unit` voor de wekelijkse
// boodschappenlijst (zie weeklyShopping.js en ingredients.js). Ontbreken
// qty/unit, dan is het een ongekwantificeerd kruid/aroma (peper, knoflook,
// kaneel naar smaak, ...) dat als naam op de lijst komt zonder hoeveelheid.
// Blikgoed/potten worden geteld in "blik"/"pak" (aantal), niet in grammen,
// omdat je nu eenmaal hele blikken koopt. "Gekookte" rijst is omgerekend naar
// ongeveer benodigde droge rijst (gekookt gewicht / 2,75).

export const RECIPES = {
  "berry-lijnzaad-yoghurt-bowl": {
    name: "Berry-lijnzaad yoghurt bowl",
    servings: 1,
    kcal: 430,
    protein: 31,
    ingredients: [
      { display: "250 g Griekse yoghurt 0–2% of skyr", key: "griekse-yoghurt", qty: 250, unit: "g" },
      { display: "125 g diepvries blauwe bessen/frambozen", key: "bessen", qty: 125, unit: "g" },
      { display: "10 g gemalen lijnzaad", key: "lijnzaad", qty: 10, unit: "g" },
      { display: "15 g walnoten, grof gehakt", key: "walnoten", qty: 15, unit: "g" },
      { display: "10 g 85% pure chocolade, fijngehakt", key: "pure-chocolade", qty: 10, unit: "g" },
      { display: "20 g havermout", key: "havermout", qty: 20, unit: "g" },
      { display: "kaneel naar smaak", key: "kaneel" },
    ],
    steps: [
      "Laat de bessen 5–10 minuten ontdooien of gebruik ze direct uit de vriezer.",
      "Roer yoghurt en havermout door elkaar.",
      "Top met bessen, lijnzaad, walnoten, chocolade en kaneel.",
    ],
    storage: "Maak de droge toppings eventueel de avond ervoor klaar; yoghurt en fruit 's ochtends toevoegen.",
  },
  "chicken-hummus-wrap": {
    name: "Chicken hummus wrap",
    servings: 2,
    kcal: 500,
    protein: 38,
    ingredients: [
      { display: "2 volkoren wraps van ±60 g", key: "volkoren-wraps", qty: 2, unit: "stuks" },
      { display: "240 g kipfilet", key: "kipfilet", qty: 240, unit: "g" },
      { display: "60 g hummus", key: "hummus", qty: 60, unit: "g" },
      { display: "80 g avocado", key: "avocado", qty: 80, unit: "g" },
      { display: "100 g tomaat", key: "tomaat", qty: 100, unit: "g" },
      { display: "100 g komkommer", key: "komkommer", qty: 100, unit: "g" },
      { display: "60 g spinazie", key: "spinazie", qty: 60, unit: "g" },
      { display: "1 tl extra vierge olijfolie", key: "olijfolie", qty: 5, unit: "g" },
      { display: "citroensap, peper, knoflookpoeder, paprikapoeder", keys: ["citroen", "peper", "knoflookpoeder", "paprikapoeder"] },
    ],
    steps: [
      "Snijd de kip in reepjes, kruid en bak in de olijfolie gaar.",
      "Besmeer de wraps met hummus.",
      "Verdeel kip, avocado, tomaat, komkommer en spinazie over de wraps.",
      "Rol strak op en snijd doormidden.",
    ],
    storage: "Kip 3 dagen gekoeld bewaren. Wraps pas vlak voor eten vullen voor de beste structuur.",
  },
  "linzen-biet-quinoa-salade": {
    name: "Linzen-biet quinoa salade",
    servings: 2,
    kcal: 510,
    protein: 27,
    ingredients: [
      { display: "120 g droge quinoa", key: "quinoa", qty: 120, unit: "g" },
      { display: "1 blik linzen, uitgelekt ±240 g", key: "linzen-blik", qty: 1, unit: "blik" },
      { display: "200 g gekookte biet, in blokjes", key: "biet", qty: 200, unit: "g" },
      { display: "100 g komkommer", key: "komkommer", qty: 100, unit: "g" },
      { display: "80 g rucola", key: "rucola", qty: 80, unit: "g" },
      { display: "50 g feta", key: "feta", qty: 50, unit: "g" },
      { display: "20 g walnoten", key: "walnoten", qty: 20, unit: "g" },
      { display: "10 g pompoenpitten", key: "pompoenpitten", qty: 10, unit: "g" },
      { display: "10 g extra vierge olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "15 g citroensap", key: "citroen" },
      { display: "mosterd, peper", keys: ["mosterd", "peper"] },
    ],
    steps: [
      "Kook quinoa volgens de verpakking en laat afkoelen.",
      "Roer olijfolie, citroensap, 1 tl mosterd en peper tot dressing.",
      "Combineer quinoa, linzen, biet, komkommer en rucola.",
      "Verdeel feta, walnoten en pompoenpitten erover en voeg dressing toe.",
    ],
    storage: "Tot 3 dagen gekoeld. Bewaar rucola en dressing apart als je mealprept.",
  },
  "cottage-cheese-egg-toast": {
    name: "Cottage cheese egg toast",
    servings: 1,
    kcal: 480,
    protein: 34,
    ingredients: [
      { display: "2 sneetjes volkorenbrood, ±80 g", key: "volkorenbrood", qty: 80, unit: "g" },
      { display: "150 g cottage cheese/hüttenkäse", key: "cottage-cheese", qty: 150, unit: "g" },
      { display: "2 eieren", key: "eieren", qty: 2, unit: "stuks" },
      { display: "50 g avocado", key: "avocado", qty: 50, unit: "g" },
      { display: "100 g tomaat", key: "tomaat", qty: 100, unit: "g" },
      { display: "5 g extra vierge olijfolie", key: "olijfolie", qty: 5, unit: "g" },
      { display: "peper, chilivlokken", keys: ["peper", "chilivlokken"] },
    ],
    steps: [
      "Kook de eieren 7–9 minuten of maak ze zacht gebakken.",
      "Rooster het brood.",
      "Beleg met cottage cheese, avocado en tomaat.",
      "Voeg de eieren toe en werk af met olijfolie, peper en chilivlokken.",
    ],
    storage: "Eieren kunnen 3–4 dagen vooraf hardgekookt worden; brood en avocado vers toevoegen.",
  },
  "egg-avocado-toast": {
    name: "Egg avocado toast",
    servings: 1,
    kcal: 490,
    protein: 31,
    ingredients: [
      { display: "2 sneetjes volkorenbrood, ±80 g", key: "volkorenbrood", qty: 80, unit: "g" },
      { display: "2 eieren", key: "eieren", qty: 2, unit: "stuks" },
      { display: "100 g cottage cheese", key: "cottage-cheese", qty: 100, unit: "g" },
      { display: "60 g avocado", key: "avocado", qty: 60, unit: "g" },
      { display: "100 g tomaat", key: "tomaat", qty: 100, unit: "g" },
      { display: "10 g pompoenpitten", key: "pompoenpitten", qty: 10, unit: "g" },
      { display: "peper, citroen", keys: ["peper", "citroen"] },
    ],
    steps: [
      "Kook de eieren 7–9 minuten.",
      "Rooster het brood en verdeel cottage cheese en avocado erover.",
      "Voeg tomaat, eieren en pompoenpitten toe.",
      "Breng op smaak met peper en een beetje citroensap.",
    ],
    storage: "Eieren vooraf koken; brood en avocado vlak voor eten bereiden.",
  },
  "chicken-quinoa-bowl": {
    name: "Chicken quinoa bowl",
    servings: 2,
    kcal: 515,
    protein: 42,
    ingredients: [
      { display: "120 g droge quinoa", key: "quinoa", qty: 120, unit: "g" },
      { display: "240 g kipfilet", key: "kipfilet", qty: 240, unit: "g" },
      { display: "200 g broccoli", key: "broccoli", qty: 200, unit: "g" },
      { display: "100 g spinazie", key: "spinazie", qty: 100, unit: "g" },
      { display: "150 g tomaat", key: "tomaat", qty: 150, unit: "g" },
      { display: "80 g avocado", key: "avocado", qty: 80, unit: "g" },
      { display: "100 g edamame, diepvries", key: "edamame", qty: 100, unit: "g" },
      { display: "10 g pompoenpitten", key: "pompoenpitten", qty: 10, unit: "g" },
      { display: "10 g extra vierge olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "citroen, knoflook, peper", keys: ["citroen", "knoflook", "peper"] },
    ],
    steps: [
      "Kook quinoa volgens de verpakking.",
      "Bak de gekruide kip gaar en snijd in plakjes.",
      "Stoom of bak broccoli en laat de spinazie kort slinken.",
      "Verdeel quinoa, groenten, edamame, kip en avocado over kommen.",
      "Top met pompoenpitten, olijfolie en citroensap.",
    ],
    storage: "Tot 3 dagen gekoeld. Avocado liefst op de dag zelf toevoegen.",
  },
  "sweet-potato-chicken-bowl": {
    name: "Sweet potato chicken bowl",
    servings: 2,
    kcal: 650,
    protein: 45,
    ingredients: [
      { display: "300 g kipfilet", key: "kipfilet", qty: 300, unit: "g" },
      { display: "400 g zoete aardappel", key: "zoete-aardappel", qty: 400, unit: "g" },
      { display: "200 g broccoli", key: "broccoli", qty: 200, unit: "g" },
      { display: "100 g boerenkool", key: "boerenkool", qty: 100, unit: "g" },
      { display: "80 g avocado", key: "avocado", qty: 80, unit: "g" },
      { display: "20 g pompoenpitten", key: "pompoenpitten", qty: 20, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "80 g Griekse yoghurt", key: "griekse-yoghurt", qty: 80, unit: "g" },
      { display: "10 g tahin", key: "tahin", qty: 10, unit: "g" },
      { display: "citroen, knoflook, komijn, peper", keys: ["citroen", "knoflook", "komijn", "peper"] },
    ],
    steps: [
      "Verwarm de oven op 200°C. Snijd zoete aardappel in blokjes en rooster met de helft van de olie 25–30 minuten.",
      "Bak kip met komijn, knoflook en peper gaar.",
      "Stoom broccoli en laat boerenkool kort slinken.",
      "Roer yoghurt, tahin, citroen en knoflook tot dressing.",
      "Verdeel over twee porties en voeg avocado en pompoenpitten pas bij het serveren toe.",
    ],
    storage: "Tot 3 dagen gekoeld; avocado/dressing apart.",
  },
  "linzen-bolognese": {
    name: "Linzen-bolognese",
    servings: 4,
    kcal: 625,
    protein: 39,
    ingredients: [
      { display: "240 g volkoren spaghetti", key: "volkoren-spaghetti", qty: 240, unit: "g" },
      { display: "2 blikken linzen, uitgelekt ±480 g", key: "linzen-blik", qty: 2, unit: "blik" },
      { display: "200 g mager rundergehakt 5% óf extra 200 g linzen", key: "rundergehakt", qty: 200, unit: "g" },
      { display: "1 ui, ±120 g", key: "ui", qty: 120, unit: "g" },
      { display: "250 g champignons", key: "champignons", qty: 250, unit: "g" },
      { display: "2 blikken tomatenblokjes, totaal ±800 g", key: "tomatenblokjes-blik", qty: 2, unit: "blik" },
      { display: "150 g spinazie", key: "spinazie", qty: 150, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "20 g Parmezaanse kaas", key: "parmezaan", qty: 20, unit: "g" },
      { display: "oregano, basilicum, knoflook, peper", keys: ["oregano", "basilicum", "knoflook", "peper"] },
    ],
    steps: [
      "Bak ui en champignons in olijfolie 5–7 minuten.",
      "Voeg rundergehakt toe en bak rul. Voor een vegetarische versie voeg je de extra linzen later toe.",
      "Voeg tomaten, linzen en kruiden toe en laat 15–20 minuten zacht koken.",
      "Roer spinazie er op het einde door.",
      "Kook pasta al dente en serveer met saus en Parmezaan.",
    ],
    storage: "4 porties; 3 dagen gekoeld of tot 3 maanden ingevroren. Pasta en saus kunnen samen bewaard worden.",
  },
  "chicken-mushroom-quinoa-skillet": {
    name: "Chicken mushroom quinoa skillet",
    servings: 2,
    kcal: 640,
    protein: 48,
    ingredients: [
      { display: "320 g kipfilet", key: "kipfilet", qty: 320, unit: "g" },
      { display: "120 g droge quinoa", key: "quinoa", qty: 120, unit: "g" },
      { display: "250 g champignons", key: "champignons", qty: 250, unit: "g" },
      { display: "200 g broccoli", key: "broccoli", qty: 200, unit: "g" },
      { display: "100 g spinazie", key: "spinazie", qty: 100, unit: "g" },
      { display: "150 g witte bonen, uitgelekt", key: "witte-bonen-blik", qty: 1, unit: "blik" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "10 g pompoenpitten", key: "pompoenpitten", qty: 10, unit: "g" },
      { display: "citroen, knoflook, tijm, peper", keys: ["citroen", "knoflook", "tijm", "peper"] },
    ],
    steps: [
      "Kook quinoa volgens de verpakking.",
      "Bak kip in olijfolie gaar en haal uit de pan.",
      "Bak champignons en broccoli 5–7 minuten.",
      "Voeg bonen en spinazie toe en verwarm tot de spinazie slinkt.",
      "Voeg kip en quinoa terug toe, breng op smaak met citroen, knoflook en tijm.",
      "Top met pompoenpitten.",
    ],
    storage: "Tot 3 dagen gekoeld; opnieuw opwarmen met een scheutje water.",
  },
  "citrus-haver-yoghurt-bowl": {
    name: "Citrus & haver yoghurt bowl",
    servings: 1,
    kcal: 445,
    protein: 31,
    ingredients: [
      { display: "250 g Griekse yoghurt 0–2% of skyr", key: "griekse-yoghurt", qty: 250, unit: "g" },
      { display: "100 g blauwe bessen", key: "bessen", qty: 100, unit: "g" },
      { display: "1 kleine sinaasappel, ±120 g vruchtvlees", key: "sinaasappel", qty: 1, unit: "stuks" },
      { display: "10 g gemalen lijnzaad", key: "lijnzaad", qty: 10, unit: "g" },
      { display: "15 g cashewnoten", key: "cashewnoten", qty: 15, unit: "g" },
      { display: "25 g havermout", key: "havermout", qty: 25, unit: "g" },
      { display: "10 g 85% pure chocolade", key: "pure-chocolade", qty: 10, unit: "g" },
    ],
    steps: [
      "Roer yoghurt met havermout en lijnzaad.",
      "Snijd de sinaasappel in stukjes.",
      "Verdeel bessen, sinaasappel, cashews en chocolade over de yoghurt.",
    ],
    storage: "Kan als overnight bowl worden voorbereid; bewaar maximaal 1 dag gekoeld.",
  },
  "chickpea-quinoa-feta-salad": {
    name: "Chickpea quinoa feta salad",
    servings: 2,
    kcal: 500,
    protein: 24,
    ingredients: [
      { display: "120 g droge quinoa", key: "quinoa", qty: 120, unit: "g" },
      { display: "1 blik kikkererwten, uitgelekt ±240 g", key: "kikkererwten-blik", qty: 1, unit: "blik" },
      { display: "100 g broccoli, fijn gesneden", key: "broccoli", qty: 100, unit: "g" },
      { display: "100 g komkommer", key: "komkommer", qty: 100, unit: "g" },
      { display: "150 g tomaat", key: "tomaat", qty: 150, unit: "g" },
      { display: "60 g feta", key: "feta", qty: 60, unit: "g" },
      { display: "60 g spinazie", key: "spinazie", qty: 60, unit: "g" },
      { display: "20 g walnoten", key: "walnoten", qty: 20, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "15 g citroensap", key: "citroen" },
      { display: "oregano, peper", keys: ["oregano", "peper"] },
    ],
    steps: [
      "Kook quinoa en laat afkoelen.",
      "Rooster of stoom broccoli kort zodat deze nog bite houdt.",
      "Combineer quinoa, kikkererwten, groenten, feta en walnoten.",
      "Maak dressing van olijfolie, citroen, oregano en peper en meng erdoor.",
    ],
    storage: "Tot 3 dagen gekoeld; dressing apart houden voor maximale houdbaarheid.",
  },
  "turkey-hummus-wrap": {
    name: "Turkey hummus wrap",
    servings: 2,
    kcal: 500,
    protein: 38,
    ingredients: [
      { display: "2 volkoren wraps, ±60 g", key: "volkoren-wraps", qty: 2, unit: "stuks" },
      { display: "240 g mager kalkoengehakt", key: "kalkoengehakt", qty: 240, unit: "g" },
      { display: "60 g hummus", key: "hummus", qty: 60, unit: "g" },
      { display: "100 g komkommer", key: "komkommer", qty: 100, unit: "g" },
      { display: "100 g tomaat", key: "tomaat", qty: 100, unit: "g" },
      { display: "60 g spinazie", key: "spinazie", qty: 60, unit: "g" },
      { display: "60 g avocado", key: "avocado", qty: 60, unit: "g" },
      { display: "1 tl olijfolie", key: "olijfolie", qty: 5, unit: "g" },
      { display: "komijn, knoflook, peper, citroen", keys: ["komijn", "knoflook", "peper", "citroen"] },
    ],
    steps: [
      "Bak het kalkoengehakt rul met komijn, knoflook en peper.",
      "Besmeer wraps met hummus.",
      "Verdeel kalkoen, groenten, spinazie en avocado over de wraps.",
      "Rol op en serveer direct.",
    ],
    storage: "Gaar kalkoengehakt tot 3 dagen gekoeld bewaren. Wrap pas vlak voor eten vullen.",
  },
  "chicken-spinach-toast": {
    name: "Chicken spinach toast",
    servings: 1,
    kcal: 480,
    protein: 38,
    ingredients: [
      { display: "2 sneetjes volkorenbrood, ±80 g", key: "volkorenbrood", qty: 80, unit: "g" },
      { display: "120 g kipfilet", key: "kipfilet", qty: 120, unit: "g" },
      { display: "100 g cottage cheese", key: "cottage-cheese", qty: 100, unit: "g" },
      { display: "60 g spinazie", key: "spinazie", qty: 60, unit: "g" },
      { display: "100 g tomaat", key: "tomaat", qty: 100, unit: "g" },
      { display: "50 g avocado", key: "avocado", qty: 50, unit: "g" },
      { display: "5 g olijfolie", key: "olijfolie", qty: 5, unit: "g" },
      { display: "peper, citroen", keys: ["peper", "citroen"] },
    ],
    steps: [
      "Bak of grill de kip gaar en snijd in plakjes.",
      "Rooster brood en beleg met cottage cheese.",
      "Voeg kip, spinazie, tomaat en avocado toe.",
      "Besprenkel met olijfolie en citroen.",
    ],
    storage: "Kip vooraf bereiden; brood en avocado vlak voor eten toevoegen.",
  },
  "tonijn-avocado-bowl": {
    name: "Tonijn-avocado bowl",
    servings: 1,
    kcal: 500,
    protein: 39,
    ingredients: [
      { display: "1 blik tonijn op water, uitgelekt ±145 g", key: "tonijn-blik", qty: 1, unit: "blik" },
      { display: "100 g gekookte zilvervliesrijst", key: "zilvervliesrijst-droog", qty: 36, unit: "g" },
      { display: "80 g avocado", key: "avocado", qty: 80, unit: "g" },
      { display: "100 g komkommer", key: "komkommer", qty: 100, unit: "g" },
      { display: "100 g tomaat", key: "tomaat", qty: 100, unit: "g" },
      { display: "60 g edamame", key: "edamame", qty: 60, unit: "g" },
      { display: "50 g spinazie", key: "spinazie", qty: 50, unit: "g" },
      { display: "10 g sesamzaad", key: "sesamzaad", qty: 10, unit: "g" },
      { display: "10 g tamari/sojasaus", key: "tamari-sojasaus", qty: 10, unit: "g" },
      { display: "limoensap", key: "limoen" },
    ],
    steps: [
      "Bereid rijst volgens de verpakking.",
      "Laat tonijn uitlekken en meng met tamari en limoensap.",
      "Combineer rijst, tonijn, groenten, edamame en avocado.",
      "Top met sesamzaad.",
    ],
    storage: "Tot 2 dagen gekoeld. Avocado liefst vlak voor eten toevoegen.",
  },
  "mediterranean-chicken-traybake": {
    name: "Mediterranean chicken traybake",
    servings: 4,
    kcal: 650,
    protein: 47,
    ingredients: [
      { display: "600 g kipfilet", key: "kipfilet", qty: 600, unit: "g" },
      { display: "500 g krieltjes", key: "krieltjes", qty: 500, unit: "g" },
      { display: "300 g broccoli", key: "broccoli", qty: 300, unit: "g" },
      { display: "250 g aubergine", key: "aubergine", qty: 250, unit: "g" },
      { display: "150 g rode ui", key: "rode-ui", qty: 150, unit: "g" },
      { display: "1 blik kikkererwten, uitgelekt ±240 g", key: "kikkererwten-blik", qty: 1, unit: "blik" },
      { display: "80 g feta", key: "feta", qty: 80, unit: "g" },
      { display: "20 g olijfolie", key: "olijfolie", qty: 20, unit: "g" },
      { display: "1 citroen", key: "citroen" },
      { display: "oregano, knoflook, peper", keys: ["oregano", "knoflook", "peper"] },
    ],
    steps: [
      "Verwarm de oven op 200°C.",
      "Halveer de krieltjes en snijd aubergine, broccoli en ui.",
      "Verdeel aardappelen, groenten en kikkererwten over een bakplaat. Meng met olijfolie en kruiden.",
      "Bak 20 minuten.",
      "Voeg gekruide kip toe en bak nog 15–18 minuten tot de kip gaar is.",
      "Verdeel feta en citroensap erover.",
    ],
    storage: "4 porties; 3 dagen gekoeld. Goed op te warmen in oven of magnetron.",
  },
  "chicken-lentil-curry": {
    name: "Chicken & lentil curry",
    servings: 4,
    kcal: 650,
    protein: 48,
    ingredients: [
      { display: "500 g kipfilet", key: "kipfilet", qty: 500, unit: "g" },
      { display: "180 g rode linzen, droog", key: "linzen-droog", qty: 180, unit: "g" },
      { display: "1 ui, ±120 g", key: "ui", qty: 120, unit: "g" },
      { display: "300 g bloemkool", key: "bloemkool", qty: 300, unit: "g" },
      { display: "200 g spinazie", key: "spinazie", qty: 200, unit: "g" },
      { display: "400 g tomatenblokjes", key: "tomatenblokjes-blik", qty: 1, unit: "blik" },
      { display: "200 ml lichte kokosmelk", key: "kokosmelk-light-blik", qty: 1, unit: "blik" },
      { display: "240 g gekookte zilvervliesrijst, per 2 porties 120 g", key: "zilvervliesrijst-droog", qty: 87, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "curry, kurkuma, komijn, knoflook, peper", keys: ["curry", "kurkuma", "komijn", "knoflook", "peper"] },
    ],
    steps: [
      "Bak ui in olijfolie 3 minuten.",
      "Voeg kipblokjes en kruiden toe en bak rondom aan.",
      "Voeg tomaat, linzen, bloemkool en kokosmelk toe.",
      "Laat 18–22 minuten zacht koken tot de linzen gaar zijn.",
      "Roer spinazie erdoor en serveer met rijst.",
    ],
    storage: "4 porties; 3 dagen gekoeld of vries 2 porties in. Bewaar rijst gekoeld en afgesloten.",
  },
  "turkey-meatballs-quinoa": {
    name: "Turkey meatballs & quinoa",
    servings: 4,
    kcal: 640,
    protein: 46,
    ingredients: [
      { display: "500 g mager kalkoengehakt", key: "kalkoengehakt", qty: 500, unit: "g" },
      { display: "1 ei", key: "eieren", qty: 1, unit: "stuks" },
      { display: "30 g havermout", key: "havermout", qty: 30, unit: "g" },
      { display: "1 ui, fijn gesneden", key: "ui", qty: 120, unit: "g" },
      { display: "400 g passata", key: "passata", qty: 1, unit: "pak" },
      { display: "200 g broccoli", key: "broccoli", qty: 200, unit: "g" },
      { display: "250 g aubergine", key: "aubergine", qty: 250, unit: "g" },
      { display: "160 g droge quinoa", key: "quinoa", qty: 160, unit: "g" },
      { display: "60 g feta", key: "feta", qty: 60, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "knoflook, oregano, peper", keys: ["knoflook", "oregano", "peper"] },
    ],
    steps: [
      "Verwarm oven op 200°C. Meng kalkoengehakt, ei, havermout, helft van de ui en kruiden. Vorm 12–16 balletjes.",
      "Bak gehaktballetjes 15–18 minuten in de oven.",
      "Kook quinoa.",
      "Bak de overige ui, aubergine en broccoli kort in olijfolie. Voeg passata toe en laat 10 minuten pruttelen.",
      "Voeg gehaktballetjes toe aan de saus en serveer met quinoa en feta.",
    ],
    storage: "4 porties; 3 dagen gekoeld of vries 2 porties in.",
  },
  "berry-pistache-yoghurt-bowl": {
    name: "Berry & pistache yoghurt bowl",
    servings: 1,
    kcal: 440,
    protein: 30,
    ingredients: [
      { display: "250 g Griekse yoghurt 0–2% of skyr", key: "griekse-yoghurt", qty: 250, unit: "g" },
      { display: "125 g aardbeien/frambozen", key: "aardbeien-frambozen", qty: 125, unit: "g" },
      { display: "10 g gemalen lijnzaad", key: "lijnzaad", qty: 10, unit: "g" },
      { display: "15 g ongezouten pistachenoten", key: "pistachenoten", qty: 15, unit: "g" },
      { display: "10 g 85% pure chocolade", key: "pure-chocolade", qty: 10, unit: "g" },
      { display: "25 g havermout", key: "havermout", qty: 25, unit: "g" },
      { display: "kaneel naar smaak", key: "kaneel" },
    ],
    steps: [
      "Roer yoghurt, havermout en lijnzaad samen.",
      "Snijd aardbeien indien nodig.",
      "Voeg fruit, pistache en chocolade toe.",
    ],
    storage: "Toppings apart bewaren als je de bowl de avond ervoor voorbereidt.",
  },
  "tonijn-kikkererwtensalade": {
    name: "Tonijn-kikkererwtensalade",
    servings: 2,
    kcal: 500,
    protein: 38,
    ingredients: [
      { display: "1 blik tonijn op water, uitgelekt ±145 g", key: "tonijn-blik", qty: 1, unit: "blik" },
      { display: "1 blik kikkererwten, uitgelekt ±240 g", key: "kikkererwten-blik", qty: 1, unit: "blik" },
      { display: "100 g komkommer", key: "komkommer", qty: 100, unit: "g" },
      { display: "150 g tomaat", key: "tomaat", qty: 150, unit: "g" },
      { display: "60 g rucola", key: "rucola", qty: 60, unit: "g" },
      { display: "80 g avocado", key: "avocado", qty: 80, unit: "g" },
      { display: "50 g Griekse yoghurt", key: "griekse-yoghurt", qty: 50, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "15 g citroensap", key: "citroen" },
      { display: "mosterd, peper, dille", keys: ["mosterd", "peper", "dille"] },
    ],
    steps: [
      "Laat tonijn en kikkererwten goed uitlekken.",
      "Snijd komkommer, tomaat en avocado.",
      "Roer yoghurt, olijfolie, citroensap, mosterd en peper tot dressing.",
      "Combineer alle ingrediënten en verdeel over twee porties.",
    ],
    storage: "Tot 2 dagen gekoeld. Voeg avocado liefst vlak voor eten toe.",
  },
  "garnalen-avocadosalade": {
    name: "Garnalen-avocadosalade",
    servings: 1,
    kcal: 480,
    protein: 35,
    ingredients: [
      { display: "150 g garnalen", key: "garnalen", qty: 150, unit: "g" },
      { display: "80 g gekookte quinoa", key: "quinoa", qty: 80, unit: "g" },
      { display: "80 g avocado", key: "avocado", qty: 80, unit: "g" },
      { display: "100 g tomaat", key: "tomaat", qty: 100, unit: "g" },
      { display: "100 g komkommer", key: "komkommer", qty: 100, unit: "g" },
      { display: "60 g spinazie/rucola", key: "spinazie", qty: 60, unit: "g" },
      { display: "50 g edamame", key: "edamame", qty: 50, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "citroen, knoflook, peper", keys: ["citroen", "knoflook", "peper"] },
    ],
    steps: [
      "Bak garnalen 2–3 minuten met knoflook tot ze gaar en net stevig zijn.",
      "Laat quinoa en garnalen kort afkoelen.",
      "Combineer met groenten, avocado en edamame.",
      "Maak af met olijfolie, citroensap en peper.",
    ],
    storage: "Het lekkerst dezelfde dag; gekoeld maximaal 1 dag bewaren.",
  },
  "garlic-shrimp-quinoa-bowl": {
    name: "Garlic shrimp quinoa bowl",
    servings: 2,
    kcal: 620,
    protein: 43,
    ingredients: [
      { display: "300 g garnalen", key: "garnalen", qty: 300, unit: "g" },
      { display: "120 g droge quinoa", key: "quinoa", qty: 120, unit: "g" },
      { display: "200 g broccoli of spruitjes", key: "broccoli", qty: 200, unit: "g" },
      { display: "100 g spinazie", key: "spinazie", qty: 100, unit: "g" },
      { display: "150 g tomaat", key: "tomaat", qty: 150, unit: "g" },
      { display: "80 g avocado", key: "avocado", qty: 80, unit: "g" },
      { display: "100 g edamame", key: "edamame", qty: 100, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "10 g pompoenpitten", key: "pompoenpitten", qty: 10, unit: "g" },
      { display: "knoflook, citroen, peper", keys: ["knoflook", "citroen", "peper"] },
    ],
    steps: [
      "Kook quinoa.",
      "Bak garnalen 2–3 minuten met knoflook en peper tot ze gaar zijn.",
      "Bak broccoli/spruitjes en voeg spinazie toe.",
      "Verdeel quinoa, groenten, edamame en garnalen over twee kommen.",
      "Voeg avocado, pompoenpitten, olijfolie en citroen toe.",
    ],
    storage: "Het liefst dezelfde dag; maximaal 1 dag gekoeld bewaren.",
  },
  "chicken-chickpea-tomato-stew": {
    name: "Chicken chickpea tomato stew",
    servings: 4,
    kcal: 650,
    protein: 49,
    ingredients: [
      { display: "500 g kipfilet", key: "kipfilet", qty: 500, unit: "g" },
      { display: "1 blik kikkererwten, uitgelekt ±240 g", key: "kikkererwten-blik", qty: 1, unit: "blik" },
      { display: "1 ui, ±120 g", key: "ui", qty: 120, unit: "g" },
      { display: "250 g aubergine", key: "aubergine", qty: 250, unit: "g" },
      { display: "400 g tomatenblokjes", key: "tomatenblokjes-blik", qty: 1, unit: "blik" },
      { display: "150 g spinazie", key: "spinazie", qty: 150, unit: "g" },
      { display: "160 g droge quinoa", key: "quinoa", qty: 160, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "knoflook, gerookt paprikapoeder, komijn, oregano, peper", keys: ["knoflook", "gerookt-paprikapoeder", "komijn", "oregano", "peper"] },
    ],
    steps: [
      "Bak ui en aubergine 5 minuten in olijfolie.",
      "Voeg kipblokjes en kruiden toe en bak rondom aan.",
      "Voeg tomaten en kikkererwten toe en laat 15 minuten zacht koken.",
      "Roer spinazie erdoor.",
      "Kook quinoa en serveer met de stoof.",
    ],
    storage: "4 porties; 3 dagen gekoeld. Quinoa apart bewaren voor de beste structuur.",
  },
  "turkey-taco-bowl": {
    name: "Turkey taco bowl",
    servings: 4,
    kcal: 650,
    protein: 45,
    ingredients: [
      { display: "500 g mager kalkoengehakt", key: "kalkoengehakt", qty: 500, unit: "g" },
      { display: "1 blik zwarte bonen, uitgelekt ±240 g", key: "zwarte-bonen-blik", qty: 1, unit: "blik" },
      { display: "240 g gekookte zilvervliesrijst", key: "zilvervliesrijst-droog", qty: 87, unit: "g" },
      { display: "150 g mais", key: "mais", qty: 150, unit: "g" },
      { display: "200 g tomaat", key: "tomaat", qty: 200, unit: "g" },
      { display: "100 g sla", key: "sla", qty: 100, unit: "g" },
      { display: "120 g avocado", key: "avocado", qty: 120, unit: "g" },
      { display: "80 g Griekse yoghurt", key: "griekse-yoghurt", qty: 80, unit: "g" },
      { display: "1 limoen", key: "limoen" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "komijn, chilipoeder, knoflook, peper", keys: ["komijn", "chilipoeder", "knoflook", "peper"] },
    ],
    steps: [
      "Bak kalkoengehakt rul in olijfolie met komijn, chili en knoflook.",
      "Voeg zwarte bonen en mais toe en verwarm kort.",
      "Verdeel rijst, sla, tomaat en het kalkoenmengsel over vier kommen.",
      "Voeg avocado toe en top met yoghurt-limoendressing.",
    ],
    storage: "4 porties; 3 dagen gekoeld. Avocado en yoghurt apart houden.",
  },
  "appel-walnoot-yoghurt-bowl": {
    name: "Appel-walnoot yoghurt bowl",
    servings: 1,
    kcal: 445,
    protein: 31,
    ingredients: [
      { display: "250 g Griekse yoghurt 0–2% of skyr", key: "griekse-yoghurt", qty: 250, unit: "g" },
      { display: "100 g blauwe bessen", key: "bessen", qty: 100, unit: "g" },
      { display: "½ grote appel, ±90 g, in blokjes", key: "appel", qty: 1, unit: "stuks" },
      { display: "10 g gemalen lijnzaad", key: "lijnzaad", qty: 10, unit: "g" },
      { display: "15 g walnoten", key: "walnoten", qty: 15, unit: "g" },
      { display: "25 g havermout", key: "havermout", qty: 25, unit: "g" },
      { display: "10 g 85% pure chocolade", key: "pure-chocolade", qty: 10, unit: "g" },
      { display: "kaneel", key: "kaneel" },
    ],
    steps: [
      "Roer yoghurt met havermout en lijnzaad.",
      "Snijd de appel in kleine blokjes.",
      "Top met bessen, appel, walnoten, chocolade en veel kaneel.",
    ],
    storage: "Appel eventueel met een beetje citroensap mengen tegen verkleuren.",
  },
  "chicken-sweet-potato-bowl": {
    name: "Chicken sweet potato bowl",
    servings: 2,
    kcal: 515,
    protein: 40,
    ingredients: [
      { display: "300 g kipfilet", key: "kipfilet", qty: 300, unit: "g" },
      { display: "400 g zoete aardappel", key: "zoete-aardappel", qty: 400, unit: "g" },
      { display: "200 g broccoli", key: "broccoli", qty: 200, unit: "g" },
      { display: "100 g boerenkool", key: "boerenkool", qty: 100, unit: "g" },
      { display: "80 g avocado", key: "avocado", qty: 80, unit: "g" },
      { display: "20 g pompoenpitten", key: "pompoenpitten", qty: 20, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "60 g Griekse yoghurt", key: "griekse-yoghurt", qty: 60, unit: "g" },
      { display: "1 tl tahin", key: "tahin", qty: 5, unit: "g" },
      { display: "citroen, knoflook, peper, komijn", keys: ["citroen", "knoflook", "peper", "komijn"] },
    ],
    steps: [
      "Verwarm de oven op 200°C. Snijd zoete aardappel in blokjes, meng met de helft van de olie en rooster 25–30 minuten.",
      "Bak de gekruide kip gaar en snijd in stukjes.",
      "Rooster/stoom broccoli en laat boerenkool kort slinken.",
      "Roer yoghurt, tahin, citroen en knoflook tot dressing.",
      "Verdeel alles over twee kommen en top met avocado en pompoenpitten.",
    ],
    storage: "Tot 3 dagen gekoeld. Avocado en dressing liefst apart bewaren.",
  },
  "chicken-sweet-potato-chili": {
    name: "Chicken sweet potato chili",
    servings: 4,
    kcal: 650,
    protein: 48,
    ingredients: [
      { display: "500 g kipfilet", key: "kipfilet", qty: 500, unit: "g" },
      { display: "400 g zoete aardappel", key: "zoete-aardappel", qty: 400, unit: "g" },
      { display: "1 blik zwarte bonen, uitgelekt ±240 g", key: "zwarte-bonen-blik", qty: 1, unit: "blik" },
      { display: "1 blik kidneybonen, uitgelekt ±240 g", key: "kidneybonen-blik", qty: 1, unit: "blik" },
      { display: "2 blikken tomatenblokjes, ±800 g", key: "tomatenblokjes-blik", qty: 2, unit: "blik" },
      { display: "1 ui, ±120 g", key: "ui", qty: 120, unit: "g" },
      { display: "150 g spinazie", key: "spinazie", qty: 150, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "80 g Griekse yoghurt", key: "griekse-yoghurt", qty: 80, unit: "g" },
      { display: "komijn, chilipoeder, gerookt paprikapoeder, knoflook, peper", keys: ["komijn", "chilipoeder", "gerookt-paprikapoeder", "knoflook", "peper"] },
    ],
    steps: [
      "Bak ui in olijfolie 3 minuten.",
      "Voeg kipblokjes, zoete aardappel en kruiden toe en bak 5 minuten.",
      "Voeg tomaten en beide soorten bonen toe.",
      "Laat 20–25 minuten zacht koken tot de zoete aardappel gaar is.",
      "Roer spinazie erdoor en serveer met een lepel Griekse yoghurt.",
    ],
    storage: "4 porties; 3 dagen gekoeld of tot 3 maanden ingevroren.",
  },
  "turkey-mushroom-rice-bowl": {
    name: "Turkey mushroom rice bowl",
    servings: 4,
    kcal: 640,
    protein: 46,
    ingredients: [
      { display: "500 g mager kalkoengehakt", key: "kalkoengehakt", qty: 500, unit: "g" },
      { display: "240 g droge zilvervliesrijst", key: "zilvervliesrijst-droog", qty: 240, unit: "g" },
      { display: "300 g champignons", key: "champignons", qty: 300, unit: "g" },
      { display: "250 g broccoli", key: "broccoli", qty: 250, unit: "g" },
      { display: "150 g spinazie", key: "spinazie", qty: 150, unit: "g" },
      { display: "10 g sesamzaad", key: "sesamzaad", qty: 10, unit: "g" },
      { display: "20 g tamari/sojasaus", key: "tamari-sojasaus", qty: 20, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "1 tl sesamolie", key: "sesamolie", qty: 5, unit: "g" },
      { display: "knoflook, gember, peper", keys: ["knoflook", "gember", "peper"] },
    ],
    steps: [
      "Kook de rijst volgens de verpakking.",
      "Bak kalkoengehakt rul in olijfolie.",
      "Voeg champignons en broccoli toe en bak 6–8 minuten.",
      "Voeg spinazie, knoflook en gember toe.",
      "Breng op smaak met tamari en een kleine hoeveelheid sesamolie.",
      "Serveer met rijst en sesamzaad.",
    ],
    storage: "4 porties; 3 dagen gekoeld. Rijst snel terugkoelen en afgesloten bewaren.",
  },
  "chickpea-chicken-curry": {
    name: "Chickpea chicken curry",
    servings: 4,
    kcal: 655,
    protein: 48,
    ingredients: [
      { display: "500 g kipfilet", key: "kipfilet", qty: 500, unit: "g" },
      { display: "1 blik kikkererwten, uitgelekt ±240 g", key: "kikkererwten-blik", qty: 1, unit: "blik" },
      { display: "300 g bloemkool", key: "bloemkool", qty: 300, unit: "g" },
      { display: "200 g spinazie", key: "spinazie", qty: 200, unit: "g" },
      { display: "400 g tomatenblokjes", key: "tomatenblokjes-blik", qty: 1, unit: "blik" },
      { display: "200 ml lichte kokosmelk", key: "kokosmelk-light-blik", qty: 1, unit: "blik" },
      { display: "240 g gekookte zilvervliesrijst", key: "zilvervliesrijst-droog", qty: 87, unit: "g" },
      { display: "10 g olijfolie", key: "olijfolie", qty: 10, unit: "g" },
      { display: "curry, kurkuma, komijn, knoflook, gember, peper", keys: ["curry", "kurkuma", "komijn", "knoflook", "gember", "peper"] },
    ],
    steps: [
      "Bak kipblokjes in olijfolie met curry, kurkuma, komijn, knoflook en gember.",
      "Voeg bloemkool, tomaat, kikkererwten en kokosmelk toe.",
      "Laat 18–20 minuten zacht koken tot kip en bloemkool gaar zijn.",
      "Roer spinazie erdoor.",
      "Serveer met zilvervliesrijst.",
    ],
    storage: "4 porties; 3 dagen gekoeld of vries 2 porties in.",
  },
};

export const WEEKS = [
  {
    number: 1,
    phase: "Menstruatiefase",
    cyclusRange: "Dag 1–7",
    focus: "Boerenkool, biet, paddenstoelen, bessen, zoete aardappel, linzen, bonen, pompoenpitten en walnoten.",
    note: "Deze week legt de nadruk op donkere bessen, groene groenten, biet, linzen en zaden. De combinatie van peulvruchten + vitamine-C-rijke groenten/fruit is handig voor de ijzeropname.",
    days: [
      { label: "Ma", ontbijt: "berry-lijnzaad-yoghurt-bowl", lunch: "chicken-hummus-wrap", snack: "Skyr + bessen", diner: "sweet-potato-chicken-bowl" },
      { label: "Di", ontbijt: "berry-lijnzaad-yoghurt-bowl", lunch: "chicken-hummus-wrap", snack: "Appel + pindakaas", diner: "sweet-potato-chicken-bowl" },
      { label: "Wo", ontbijt: "berry-lijnzaad-yoghurt-bowl", lunch: "linzen-biet-quinoa-salade", snack: "Edamame", diner: "linzen-bolognese" },
      { label: "Do", ontbijt: "berry-lijnzaad-yoghurt-bowl", lunch: "linzen-biet-quinoa-salade", snack: "Cottage cheese + peer", diner: "linzen-bolognese" },
      { label: "Vr", ontbijt: "berry-lijnzaad-yoghurt-bowl", lunch: "cottage-cheese-egg-toast", snack: "2 eieren + mandarijn", diner: "chicken-mushroom-quinoa-skillet" },
      { label: "Za", ontbijt: "berry-lijnzaad-yoghurt-bowl", lunch: "egg-avocado-toast", snack: "Skyr + banaan", diner: "chicken-mushroom-quinoa-skillet" },
      { label: "Zo", ontbijt: "berry-lijnzaad-yoghurt-bowl", lunch: "chicken-quinoa-bowl", snack: "Walnoten + fruit", diner: null },
    ],
  },
  {
    number: 2,
    phase: "Folliculaire fase",
    cyclusRange: "Dag 8–14",
    focus: "Groene groenten, linzen, kikkererwten, citrus, avocado, haver, eieren en gevarieerde volkoren granen.",
    note: "Een frisse, groene week met extra citrus, avocado, linzen, kikkererwten en eieren. Veel gerechten zijn licht maar nog steeds eiwitrijk.",
    days: [
      { label: "Ma", ontbijt: "citrus-haver-yoghurt-bowl", lunch: "egg-avocado-toast", snack: "Skyr + kiwi", diner: "mediterranean-chicken-traybake" },
      { label: "Di", ontbijt: "citrus-haver-yoghurt-bowl", lunch: "egg-avocado-toast", snack: "Appel + amandelen", diner: "mediterranean-chicken-traybake" },
      { label: "Wo", ontbijt: "citrus-haver-yoghurt-bowl", lunch: "chickpea-quinoa-feta-salad", snack: "Edamame", diner: "chicken-lentil-curry" },
      { label: "Do", ontbijt: "citrus-haver-yoghurt-bowl", lunch: "chickpea-quinoa-feta-salad", snack: "Cottage cheese + aardbeien", diner: "chicken-lentil-curry" },
      { label: "Vr", ontbijt: "citrus-haver-yoghurt-bowl", lunch: "turkey-hummus-wrap", snack: "2 eieren + fruit", diner: "turkey-meatballs-quinoa" },
      { label: "Za", ontbijt: "citrus-haver-yoghurt-bowl", lunch: "chicken-spinach-toast", snack: "Skyr + banaan", diner: "turkey-meatballs-quinoa" },
      { label: "Zo", ontbijt: "citrus-haver-yoghurt-bowl", lunch: "tonijn-avocado-bowl", snack: "Noten + mandarijn", diner: null },
    ],
  },
  {
    number: 3,
    phase: "Ovulatiefase",
    cyclusRange: "Dag 15–21",
    focus: "Tomaat, spinazie, spruitjes, quinoa, bessen, avocado, linzen, amandelen/pistache en af en toe garnalen.",
    note: "Hier komen tomaat, bessen, quinoa en veel groenten terug. Garnalen staan één keer gepland; vervang ze gerust door kip als je geen zin hebt in vis/schaaldieren.",
    days: [
      { label: "Ma", ontbijt: "berry-pistache-yoghurt-bowl", lunch: "chicken-quinoa-bowl", snack: "Skyr + frambozen", diner: "garlic-shrimp-quinoa-bowl" },
      { label: "Di", ontbijt: "berry-pistache-yoghurt-bowl", lunch: "chicken-quinoa-bowl", snack: "Appel + amandelen", diner: "garlic-shrimp-quinoa-bowl" },
      { label: "Wo", ontbijt: "berry-pistache-yoghurt-bowl", lunch: "tonijn-kikkererwtensalade", snack: "Edamame", diner: "chicken-chickpea-tomato-stew" },
      { label: "Do", ontbijt: "berry-pistache-yoghurt-bowl", lunch: "tonijn-kikkererwtensalade", snack: "Cottage cheese + kiwi", diner: "chicken-chickpea-tomato-stew" },
      { label: "Vr", ontbijt: "berry-pistache-yoghurt-bowl", lunch: "cottage-cheese-egg-toast", snack: "2 eieren + fruit", diner: "turkey-taco-bowl" },
      { label: "Za", ontbijt: "berry-pistache-yoghurt-bowl", lunch: "garnalen-avocadosalade", snack: "Skyr + banaan", diner: "turkey-taco-bowl" },
      { label: "Zo", ontbijt: "berry-pistache-yoghurt-bowl", lunch: "chicken-quinoa-bowl", snack: "Pistachenoten + fruit", diner: null },
    ],
  },
  {
    number: 4,
    phase: "Luteale fase",
    cyclusRange: "Dag 22–28",
    focus: "Zoete aardappel, koolsoorten, appel/peer, kikkererwten, bruine rijst, sesam en walnoten.",
    note: "In deze fase mag je iets meer ruimte laten voor honger. De maaltijden bevatten extra vezels en complexe koolhydraten zoals zoete aardappel, bonen en zilvervliesrijst.",
    days: [
      { label: "Ma", ontbijt: "appel-walnoot-yoghurt-bowl", lunch: "chicken-sweet-potato-bowl", snack: "Skyr + banaan + kaneel", diner: "chicken-sweet-potato-chili" },
      { label: "Di", ontbijt: "appel-walnoot-yoghurt-bowl", lunch: "chicken-sweet-potato-bowl", snack: "Appel + pindakaas", diner: "chicken-sweet-potato-chili" },
      { label: "Wo", ontbijt: "appel-walnoot-yoghurt-bowl", lunch: "chickpea-quinoa-feta-salad", snack: "Cottage cheese + peer", diner: "turkey-mushroom-rice-bowl" },
      { label: "Do", ontbijt: "appel-walnoot-yoghurt-bowl", lunch: "chickpea-quinoa-feta-salad", snack: "Edamame", diner: "turkey-mushroom-rice-bowl" },
      { label: "Vr", ontbijt: "appel-walnoot-yoghurt-bowl", lunch: "chicken-spinach-toast", snack: "2 eieren + fruit", diner: "chickpea-chicken-curry" },
      { label: "Za", ontbijt: "appel-walnoot-yoghurt-bowl", lunch: "tonijn-kikkererwtensalade", snack: "Skyr + bessen", diner: "chickpea-chicken-curry" },
      { label: "Zo", ontbijt: "appel-walnoot-yoghurt-bowl", lunch: "egg-avocado-toast", snack: "Walnoten + peer", diner: null },
    ],
  },
];

export const SNACK_GUIDE = [
  { name: "Skyr + bessen", portion: "170 g skyr + 100 g bessen", kcal: "±130 kcal", protein: "±18 g eiwit" },
  { name: "Skyr + banaan", portion: "170 g skyr + ½–1 banaan", kcal: "±170–220 kcal", protein: "±18 g eiwit" },
  { name: "Appel + pindakaas", portion: "1 appel + 15 g pindakaas", kcal: "±175 kcal", protein: "±4 g eiwit" },
  { name: "Cottage cheese + fruit", portion: "150 g cottage cheese + 100 g fruit", kcal: "±150–180 kcal", protein: "±18 g eiwit" },
  { name: "Edamame", portion: "150 g edamame", kcal: "±180 kcal", protein: "±17 g eiwit" },
  { name: "2 eieren + fruit", portion: "2 eieren + 1 stuk fruit", kcal: "±200–230 kcal", protein: "±13 g eiwit" },
  { name: "Noten + fruit", portion: "20 g walnoten/amandelen + 1 stuk fruit", kcal: "±190–220 kcal", protein: "±4 g eiwit" },
];
